language: node_js
notifications:
  email: "869235582@qq.com"
sudo: false
node_js:
  - "8"
install:
  - npm install
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: npm run compile
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
